# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/system_jesd204_phy_0_0.xci
# IP: The module: 'system_jesd204_phy_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/ip_0/system_jesd204_phy_0_0_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_jesd204_phy_0_0_gt || ORIG_REF_NAME==system_jesd204_phy_0_0_gt} -quiet] -quiet

# XDC: d:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/synth/system_jesd204_phy_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_jesd204_phy_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/synth/system_jesd204_phy_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_jesd204_phy_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/synth/system_jesd204_phy_0_0_clock_group.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_jesd204_phy_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/synth/system_jesd204_phy_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_jesd204_phy_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/ip_0/synth/system_jesd204_phy_0_0_gt_ooc.xdc

# XDC: d:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/ip_0/synth/system_jesd204_phy_0_0_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_jesd204_phy_0_0_gt || ORIG_REF_NAME==system_jesd204_phy_0_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# IP: D:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/system_jesd204_phy_0_0.xci
# IP: The module: 'system_jesd204_phy_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/ip_0/system_jesd204_phy_0_0_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_jesd204_phy_0_0_gt || ORIG_REF_NAME==system_jesd204_phy_0_0_gt} -quiet] -quiet

# XDC: d:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/synth/system_jesd204_phy_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_jesd204_phy_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/synth/system_jesd204_phy_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_jesd204_phy_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/synth/system_jesd204_phy_0_0_clock_group.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_jesd204_phy_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/synth/system_jesd204_phy_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_jesd204_phy_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/ip_0/synth/system_jesd204_phy_0_0_gt_ooc.xdc

# XDC: d:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/ip_0/synth/system_jesd204_phy_0_0_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_jesd204_phy_0_0_gt || ORIG_REF_NAME==system_jesd204_phy_0_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet
