#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.1.3 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Dec 15 12:48:01 +0400 2022
# SW Build 2644227 on Wed Sep  4 09:45:24 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_5 zynq_ultra_ps_e_vip_v1_0_5 axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_21 proc_sys_reset_v5_0_13 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_19 fifo_generator_v13_2_4 axi_data_fifo_v2_1_18 axi_crossbar_v2_1_20 dist_mem_gen_v8_0_13 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 lib_fifo_v1_0_13 axi_quad_spi_v3_2_18 axi_uartlite_v2_0_23 jesd204_v7_2_6 gtwizard_ultrascale_v1_7_6 xlconstant_v1_1_6 xbip_utils_v3_0_10 axi_utils_v2_0_6 xbip_pipe_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_15 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_dsp48_multadd_v3_0_6 dds_compiler_v6_0_18 xlslice_v1_0_2 axi_protocol_converter_v2_1_19)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2019.1.3 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/d4a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_zynq_ultra_ps_e_0_0/sim/system_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_21 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/9c6e/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_gpio_0_0/sim/system_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_rst_ps8_0_96M_0/sim/system_rst_ps8_0_96M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/4d88/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/1f5a/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_4 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5b9c/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ace7/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work dist_mem_gen_v8_0_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/0bf5/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/4dac/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_quad_spi_v3_2_18 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/488f/hdl/axi_quad_spi_v3_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_quad_spi_0_0/sim/system_axi_quad_spi_0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_gpio_0_1/sim/system_axi_gpio_0_1.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_gpio_0_2/sim/system_axi_gpio_0_2.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_gpio_0_3/sim/system_axi_gpio_0_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_23 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/0315/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_uartlite_0_0/sim/system_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work jesd204_v7_2_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/0565/hdl/jesd204_v7_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_0_0/synth/system_jesd204_0_0_block.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_0_0/synth/axi_ipif/system_jesd204_0_0_address_decoder.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_0_0/synth/system_jesd204_0_0_register_decode.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_0_0/synth/axi_ipif/system_jesd204_0_0_axi_lite_ipif.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_0_0/synth/axi_ipif/system_jesd204_0_0_counter_f.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_0_0/synth/axi_ipif/system_jesd204_0_0_pselect_f.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_0_0/synth/axi_ipif/system_jesd204_0_0_slave_attachment.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_0_0/synth/system_jesd204_0_0_reset_block.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_0_0/synth/system_jesd204_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gtwizard_ultrascale_v1_7_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/5767/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_phy_0_0/ip_0/sim/gtwizard_ultrascale_v1_7_gthe4_channel.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_phy_0_0/ip_0/sim/system_jesd204_phy_0_0_gt_gthe4_channel_wrapper.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_phy_0_0/ip_0/sim/system_jesd204_phy_0_0_gt_gtwizard_gthe4.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_phy_0_0/ip_0/sim/system_jesd204_phy_0_0_gt_gtwizard_top.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_phy_0_0/ip_0/sim/system_jesd204_phy_0_0_gt.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_phy_0_0/synth/system_jesd204_phy_0_0_block.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_phy_0_0/synth/system_jesd204_phy_0_0_sync_block.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_phy_0_0/synth/system_jesd204_phy_0_0_support.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_phy_0_0/synth/system_jesd204_phy_0_0_gt_common_wrapper.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_phy_0_0/synth/gtwizard_ultrascale_v1_7_gthe4_common.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_phy_0_0/synth/system_jesd204_phy_0_0_gt_common.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_phy_0_0/synth/system_jesd204_phy_0_0_reset_control.v" \
    "$ref_dir/../../../bd/system/ip/system_jesd204_phy_0_0/synth/system_jesd204_phy_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_util_ds_buf_1_0/util_ds_buf.vhd" \
    "$ref_dir/../../../bd/system/ip/system_util_ds_buf_1_0/sim/system_util_ds_buf_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/66e7/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xlconstant_0_0/sim/system_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_util_ds_buf_0_0/sim/system_util_ds_buf_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xlconstant_0_1/sim/system_xlconstant_0_1.v" \
    "$ref_dir/../../../bd/system/ip/system_xlconstant_0_2/sim/system_xlconstant_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_util_ds_buf_2_0/sim/system_util_ds_buf_2_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_util_ds_buf_sysref_0/sim/system_util_ds_buf_sysref_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/edit_modulator_v1_0.srcs/sources_1/bd/design_1/ipshared/1123/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/edit_modulator_v1_0.srcs/sources_1/bd/design_1/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/edit_modulator_v1_0.srcs/sources_1/bd/design_1/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/edit_modulator_v1_0.srcs/sources_1/bd/design_1/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_15 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/edit_modulator_v1_0.srcs/sources_1/bd/design_1/ipshared/d4d2/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/edit_modulator_v1_0.srcs/sources_1/bd/design_1/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/edit_modulator_v1_0.srcs/sources_1/bd/design_1/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/edit_modulator_v1_0.srcs/sources_1/bd/design_1/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work dds_compiler_v6_0_18 $vhdlan_opts \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/edit_modulator_v1_0.srcs/sources_1/bd/design_1/ipshared/ce25/hdl/dds_compiler_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/edit_modulator_v1_0.srcs/sources_1/bd/design_1/ip/design_1_dds_compiler_0_0/sim/design_1_dds_compiler_0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/edit_modulator_v1_0.srcs/sources_1/bd/design_1/ip/design_1_dds_compiler_0_1/sim/design_1_dds_compiler_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/edit_modulator_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_0_0/sim/design_1_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/system/ipshared/edit_modulator_v1_0.srcs/sources_1/bd/design_1/sim/design_1.v" \
    "$ref_dir/../../../bd/system/ipshared/src/data_conv.v" \
    "$ref_dir/../../../bd/system/ipshared/edit_modulator_v1_0.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v" \
    "$ref_dir/../../../bd/system/ipshared/src/lfm.v" \
    "$ref_dir/../../../bd/system/ipshared/02f7/hdl/modulator_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/system/ipshared/02f7/hdl/modulator_v1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_modulator_0_0/sim/system_modulator_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_gpio_0_4/sim/system_axi_gpio_0_4.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/f044/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xlslice_0_0/sim/system_xlslice_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_xlslice_jesd_reset_0/sim/system_xlslice_jesd_reset_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c83a/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ipshared/c923" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../alinx_test.srcs/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
    "$ref_dir/../../../bd/system/sim/system.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
