set_property SRC_FILE_INFO {cfile:d:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/synth/system_jesd204_phy_0_0.xdc rfile:../../../alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/synth/system_jesd204_phy_0_0.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/atom/program/mwsystems/test/acu9eg_ad9173/alinx_test/alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/ip_0/synth/system_jesd204_phy_0_0_gt.xdc rfile:../../../alinx_test.srcs/sources_1/bd/system/ip/system_jesd204_phy_0_0/ip_0/synth/system_jesd204_phy_0_0_gt.xdc id:2 order:EARLY scoped_inst:inst/jesd204_phy_block_i/system_jesd204_phy_0_0_gt_i/inst} [current_design]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-1 -description {Safe RW control registers} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*_transDbgCtrl_*x_i/*_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*_transDbgCtrl_*x_i/slv_rdata_reg[*]}] ]
set_property src_info {type:SCOPED_XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-1 -description {Safe RW control registers} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*axi_register_if_i/slv_addr_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~CE} -of [get_cells -hier -filter {name=~*_transDbgCtrl_*x_i/*_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-1 -description {Safe RX RW control registers} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*axi_register_if_i/slv_addr_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*_transDbgCtrl_*x_i/*_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-1 -description {Safe RW control registers} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*_transDbgCtrl_*x_i/slv_rden_r_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~CE} -of [get_cells -hier -filter {name=~*_transDbgCtrl_*x_i/*_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-1 -description {Safe RX RW control registers} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*_transDbgCtrl_*x_i/slv_rden_r_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*_transDbgCtrl_*x_i/*_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-1 -description {GT_WIZ cpll cal block is safe} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*_transDbgCtrl_async_i/*_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*_cpll_cal_*x_i/*cpll_cal_state_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-1 -description {GT_WIZ cpll cal block is safe} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*_transDbgCtrl_async_i/*_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*_cpll_cal_*x_i/cal_fail_store_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-1 -description {GT_WIZ cpll cal block is safe} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*_transDbgCtrl_async_i/*_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~CE} -of [get_cells -hier -filter {name=~*_cpll_cal_*x_i/*repeat_ctr_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-1 -description {GT_WIZ cpll cal block is safe} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*_transDbgCtrl_async_i/*_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*_gt*e4_cpll_cal_*x_i/gen_cal_*x_en.cal_fail_store_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-1 -description {DRP mailbox control is safe} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*Mailbox_i/drp_if_select_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~CE} -of [get_cells -hier -filter {name=~*_drp_arb_i*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-1 -description {DRP mailbox control is safe} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*Mailbox_i/drp_if_select_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~CE} -of [get_cells -hier -filter {name=~*Mailbox_i/drp_read_data_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-1 -description {DRP mailbox control is safe} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*Mailbox_i/access_type_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~CE} -of [get_cells -hier -filter {name=~*Mailbox_i/drp_read_data_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-1 -description {DRP mailbox control is safe} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*Mailbox_i/drp_if_select_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*Mailbox_i/clk2clk_handshake_pulse_gen_i/clk2_ready_reg}] ]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-1 -description {DRP mailbox selector is safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~Mailbox_i/drp_if_select_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-1 -description {GT channel control select is safe} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*_phyAxiConfig_i/gt_interface_sel_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*_transDbgCtrl_*x_i/*_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-1 -description {GT channel control select is safe} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*_phyAxiConfig_i/gt_interface_sel_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~CE} -of [get_cells -hier -filter {name=~*_transDbgCtrl_*x_i/*_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-1 -description {XPLLCLKSEL is safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*_transDbgCtrl_async_i/*xpllclksel_reg[*]}] ] -to   [ get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*_block_i/*x_pll_lock_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-2 -description {RXPLLCLKSEL is safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*_transDbgCtrl_async_i/*xpllclksel_reg*}] ] -to   [ get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*x_pll_lock_reg}] ]
set_property src_info {type:SCOPED_XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-10 -description {GT_WIZ reset_smc TX reset done synchroniser is safe} -from [ get_pins -hier -filter {REF_PIN_NAME=~RXUSRCLK2} ] -to   [ get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*RXRESETDONE/data_sync_reg1}] ]
set_property src_info {type:SCOPED_XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-10 -description {GT_WIZ reset_smc TX reset done synchroniser is safe} -from [ get_pins -hier -filter {REF_PIN_NAME=~TXUSRCLK2} ] -to   [ get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*TXRESETDONE/data_sync_reg1}] ]
set_property src_info {type:SCOPED_XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-10 -description {GT_WIZ cpll cal block is safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*USER_CPLLLOCK_OUT_reg}] ] -to   [ get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*syncstages_ff_reg[0]}] ]
set_property src_info {type:SCOPED_XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-10 -description {GT_WIZ cpll cal block is safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*_transDbgCtrl_async_i/*xpllclksel_reg[*]}] ] -to   [ get_pins -filter {REF_PIN_NAME=~PRE} -of [get_cells -hier -filter {name=~*_cpll_cal_inst/reset_synchronizer_resetin_*x_inst/rst_in_meta_reg}] ]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-10 -description {GT_WIZ cpll cal block is safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*_transDbgCtrl_async_i/cpll_pd_*_reg}] ] -to   [ get_pins -filter {REF_PIN_NAME=~PRE} -of [get_cells -hier -filter {name=~*_cpll_cal_inst/reset_synchronizer_resetin_*x_inst/rst_in_meta_reg}] ]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-10 -description {GT_WIZ cpll cal block is safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*cpll_cal_*x_i/gen_cal_*x_en.mask_user_in_reg}] ] -to   [ get_pins -filter {REF_PIN_NAME=~PRE} -of [get_cells -hier -filter {name=~*xpm_cdc_async_rst_inst/arststages_ff_reg[0]}] ]
set_property src_info {type:SCOPED_XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-10 -description {Block is safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*_transDbgCtrl_async_i/*x_sys_reset_axi_reg}] ] -to   [ get_pins -filter {REF_PIN_NAME=~PRE} -of [get_cells -hier -filter {name=~*_reset_all/xpm_cdc_async_rst_inst/arststages_ff_reg[0]}] ]
set_property src_info {type:SCOPED_XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-10 -description {RXRESETDONE synchroniser is safe} -to   [ get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*sync_RXRESETDONE/data_sync_reg1}] ]
set_property src_info {type:SCOPED_XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-10 -description {XPLLCLKSEL is safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*_transDbgCtrl_async_i/*xpllclksel_reg*}] ] -to   [ get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*x_pll_lock_reg}] ]
set_property src_info {type:SCOPED_XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-10 -description {GT_WIZ cpll cal block is safe} -to   [ get_pins -filter {REF_PIN_NAME=~PRE} -of [get_cells -hier -filter {name=~*sync_gtwiz_userclk_tx_active/xpm_cdc_async_rst_inst/arststages_ff_reg[0]}] ]
set_property src_info {type:SCOPED_XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-11 -description {GT_WIZ cpll call block is safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*OUTCLK_FREQ_COUNTER/state_reg[0]}] ] -to   [ get_pins -filter {REF_PIN_NAME=~PRE} -of [get_cells -hier -filter {name=~*rst_in_meta_reg}] ]
set_property src_info {type:SCOPED_XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-11 -description {GT_WIZ cpll call block is safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*OUTCLK_FREQ_COUNTER/state_reg[0]}] ] -to   [ get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*OUTCLK_FREQ_COUNTER/tstclk_rst_dly1_reg}] ]
set_property src_info {type:SCOPED_XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-11 -description {Safe Synchroniser} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*x_pll_lock_i_reg}] ] -to   [ get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*cdc_i/syncstages_ff_reg[0]}] ]
set_property src_info {type:SCOPED_XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-12 -description {RXRESETDONE synchroniser is safe} -to   [ get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*sync_RXRESETDONE/data_sync_reg1}] ]
set_property src_info {type:SCOPED_XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-13 -description {DRP mailbox selector is safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*Mailbox_i/drp_if_select_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-13 -description {DRP mailbox selector is safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*Mailbox_i/access_type_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-14 -description {DRP mailbox is safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*drpChannelMailbox_i/drp_int_addr_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-14 -description {DRP mailbox is safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*drpChannelMailbox_i/drp_write_data_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-14 -description {DRP mailbox is safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*drpCommonMailbox_i/drp_int_addr_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-14 -description {DRP mailbox is safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*drpCommonMailbox_i/drp_write_data_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-15 -description {Safe, warning only} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*Mailbox_i/drp_read_data_reg*}] ] -to   [ get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*axi_register_if_i/axi_rdata_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-15 -description {Safe, warning only} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*Mailbox_i/drp_if_select_reg*}] ] -to   [ get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*Mailbox_i/drp_read_data_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-15 -description {Safe, warning only} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*transDbgCtrl_rx_i/slv_wdata_r_internal_reg*}] ] -to   [ get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*hold_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -quiet -user JESD204_PHY -type CDC -id CDC-15 -description {Safe, warning only} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*transDbgCtrl_tx_i/slv_wdata_r_internal_reg*}] ] -to   [ get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*transDbgCtrl_tx_i/txdiffctrl*}] ]
current_instance
current_instance inst/jesd204_phy_block_i/system_jesd204_phy_0_0_gt_i/inst
set_property src_info {type:SCOPED_XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y4 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[1].*gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST}]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/jesd204_phy_block_i/system_jesd204_phy_0_0_gt_i/inst/gen_gtwizard_gthe4_top.system_jesd204_phy_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_pwrgood_delay_inst[0].delay_powergood_inst/gen_powergood_delay.pwr_on_fsm_reg/Q}]
current_instance inst/jesd204_phy_block_i/system_jesd204_phy_0_0_gt_i/inst
set_property src_info {type:SCOPED_XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y5 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[1].*gen_gthe4_channel_inst[1].GTHE4_CHANNEL_PRIM_INST}]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/jesd204_phy_block_i/system_jesd204_phy_0_0_gt_i/inst/gen_gtwizard_gthe4_top.system_jesd204_phy_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_pwrgood_delay_inst[1].delay_powergood_inst/gen_powergood_delay.pwr_on_fsm_reg/Q}]
current_instance inst/jesd204_phy_block_i/system_jesd204_phy_0_0_gt_i/inst
set_property src_info {type:SCOPED_XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y6 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[1].*gen_gthe4_channel_inst[2].GTHE4_CHANNEL_PRIM_INST}]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/jesd204_phy_block_i/system_jesd204_phy_0_0_gt_i/inst/gen_gtwizard_gthe4_top.system_jesd204_phy_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_pwrgood_delay_inst[2].delay_powergood_inst/gen_powergood_delay.pwr_on_fsm_reg/Q}]
current_instance inst/jesd204_phy_block_i/system_jesd204_phy_0_0_gt_i/inst
set_property src_info {type:SCOPED_XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y7 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[1].*gen_gthe4_channel_inst[3].GTHE4_CHANNEL_PRIM_INST}]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/jesd204_phy_block_i/system_jesd204_phy_0_0_gt_i/inst/gen_gtwizard_gthe4_top.system_jesd204_phy_0_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_pwrgood_delay_inst[3].delay_powergood_inst/gen_powergood_delay.pwr_on_fsm_reg/Q}]
