webtalk_init -webtalk_dir D:\\atom\\program\\mwsystems\\alinx_test\\alinx_test.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2022-09-05 19:47:44" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "vsud0h5hh1h3sdvhgsp02fqqc5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 3700X 8-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3593 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.288 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1662391421293" -context "sdk\\\\hardware/1662391421293"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1662391421293"
webtalk_add_data -client sdk -key isZynqMP -value "true" -context "sdk\\\\hardware/1662391421293"
webtalk_add_data -client sdk -key Processors -value "7" -context "sdk\\\\hardware/1662391421293"
webtalk_add_data -client sdk -key VivadoVersion -value "2019.1.3" -context "sdk\\\\hardware/1662391421293"
webtalk_add_data -client sdk -key Arch -value "zynquplus" -context "sdk\\\\hardware/1662391421293"
webtalk_add_data -client sdk -key Device -value "xczu9eg" -context "sdk\\\\hardware/1662391421293"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1662391421293"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1662391421293"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1662391421293"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1662391421293"
webtalk_add_data -client sdk -key uid -value "1662391478291" -context "sdk\\\\bsp/1662391478291"
webtalk_add_data -client sdk -key hwid -value "1662391421293" -context "sdk\\\\bsp/1662391478291"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1662391478291"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1662391478291"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1662391478291"
webtalk_add_data -client sdk -key uid -value "1662391483259" -context "sdk\\\\application/1662391483259"
webtalk_add_data -client sdk -key hwid -value "1662391421293" -context "sdk\\\\application/1662391483259"
webtalk_add_data -client sdk -key bspid -value "1662391478291" -context "sdk\\\\application/1662391483259"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1662391483259"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1662391483259"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1662391483259"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1662391483259"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1662391483259"
webtalk_add_data -client sdk -key Procused -value "psu_cortexa53" -context "sdk\\\\application/1662391483259"
webtalk_add_data -client sdk -key projSize -value "232.953125" -context "sdk\\\\application/1662391483259"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1662392864007"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1662392864007"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1662392864007"
webtalk_add_data -client sdk -key DebugCount -value "2" -context "sdk\\\\bsp/1662392864007"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1662392864007"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1662392864007"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1662392864007"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1662392864007"
webtalk_transmit -clientid 2529022947 -regid "" -xml D:\\atom\\program\\mwsystems\\alinx_test\\alinx_test.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\atom\\program\\mwsystems\\alinx_test\\alinx_test.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\atom\\program\\mwsystems\\alinx_test\\alinx_test.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
